# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloximages < Formula
  desc "CueBlox"
  homepage "https://github.com/cueblox/"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/bloximages/releases/download/v0.0.5/bloximages_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "da9b3e5230c8804553970cbc768701b434ccbfac325b700f9129b0b3c0c758b7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cueblox/bloximages/releases/download/v0.0.5/bloximages_0.0.5_Darwin_arm64.tar.gz"
      sha256 "edeac28d794f0dcd0930acd2cf68a7a5f330a056e113c3522bbf48697ef1c599"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/bloximages/releases/download/v0.0.5/bloximages_0.0.5_Linux_x86_64.tar.gz"
      sha256 "a08c4e7470351c72a03628e22f4b3b5f54e483f4a076928f260eddde845eef55"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cueblox/bloximages/releases/download/v0.0.5/bloximages_0.0.5_Linux_arm64.tar.gz"
      sha256 "f98ec6297b9b703ac43c3cfbcebc41eb595cdc84212cb4368f484b88434d5c4e"
    end
  end

  def install
    bin.install "bloximages"
  end
end
