# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blox < Formula
  desc "CueBlox"
  homepage "https://github.com/cueblox/"
  version "0.4.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/cueblox/blox/releases/download/v0.4.2/blox_0.4.2_Darwin_x86_64.tar.gz"
    sha256 "0185e67991a818d4dde1c2cf0f21af33a8c576920e4e3959c1ca29b251d45744"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/cueblox/blox/releases/download/v0.4.2/blox_0.4.2_Darwin_arm64.tar.gz"
    sha256 "c02f4b23ba032d985c89188d25b7f8068843c0fef4ac28208bb644fdbbfabd94"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cueblox/blox/releases/download/v0.4.2/blox_0.4.2_Linux_x86_64.tar.gz"
    sha256 "942f04945b78c575be872f1b82fab000aaa5f604d6d24b5cadca0361fcd3eeef"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/cueblox/blox/releases/download/v0.4.2/blox_0.4.2_Linux_arm64.tar.gz"
    sha256 "b2524a08126631b5c379e0bc822917af3d30c626785908bb8b23f042d19a46eb"
  end

  def install
    bin.install "blox"
    bash_completion.install "completions/blox.bash" => "blox"
    zsh_completion.install "completions/blox.zsh" => "_blox"
    fish_completion.install "completions/blox.fish"
  end

  test do
    system "#{bin}/blox -v"
  end
end
