# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blox < Formula
  desc "CueBlox"
  homepage "https://github.com/cueblox/"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/blox/releases/download/v0.7.3/blox_0.7.3_Darwin_x86_64.tar.gz"
      sha256 "b14b0b25829c5df9e7759af66e24807c7b52f407e3a135885790999fc824391c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cueblox/blox/releases/download/v0.7.3/blox_0.7.3_Darwin_arm64.tar.gz"
      sha256 "6ec0b90ef9daea3cc6fcb028c1904036a8429be14d63f4def066877c7fa54710"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/blox/releases/download/v0.7.3/blox_0.7.3_Linux_x86_64.tar.gz"
      sha256 "915a8b6e49ce2717d3c9ef66c2778ab434e7251bfd56740013d1e3e30fad562e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cueblox/blox/releases/download/v0.7.3/blox_0.7.3_Linux_arm64.tar.gz"
      sha256 "7d2f3f92cbc6f3d2cdea6763b5db03b0be8caf1d52e995e113927467f80c3a66"
    end
  end

  def install
    bin.install "blox"
    bash_completion.install "completions/blox.bash" => "blox"
    zsh_completion.install "completions/blox.zsh" => "_blox"
    fish_completion.install "completions/blox.fish"
  end

  test do
    system "#{bin}/blox -v"
  end
end
