# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blox < Formula
  desc "CueBlox"
  homepage "https://github.com/cueblox/"
  version "0.7.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/blox/releases/download/v0.7.5/blox_0.7.5_Darwin_x86_64.tar.gz"
      sha256 "3fdc18bca8203c4289de31f0bf2217d1f63ca8e0b3f3df044748453236df007d"

      def install
        bin.install "blox"
        bash_completion.install "completions/blox.bash" => "blox"
        zsh_completion.install "completions/blox.zsh" => "_blox"
        fish_completion.install "completions/blox.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cueblox/blox/releases/download/v0.7.5/blox_0.7.5_Darwin_arm64.tar.gz"
      sha256 "d1ef150de502f88c5db7f7832b6b01fb1c6eb8fa9495d27caac7527dc34d0828"

      def install
        bin.install "blox"
        bash_completion.install "completions/blox.bash" => "blox"
        zsh_completion.install "completions/blox.zsh" => "_blox"
        fish_completion.install "completions/blox.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cueblox/blox/releases/download/v0.7.5/blox_0.7.5_Linux_arm64.tar.gz"
      sha256 "f28ce4681a1b60b8a37c5fa82f3c78d91bc0afef30a635f0a394346cff7c99eb"

      def install
        bin.install "blox"
        bash_completion.install "completions/blox.bash" => "blox"
        zsh_completion.install "completions/blox.zsh" => "_blox"
        fish_completion.install "completions/blox.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cueblox/blox/releases/download/v0.7.5/blox_0.7.5_Linux_x86_64.tar.gz"
      sha256 "27c0909a8184dda1f9d9eea271a09f66c18f72c9c4d5f9c19b75d6d74b29f59a"

      def install
        bin.install "blox"
        bash_completion.install "completions/blox.bash" => "blox"
        zsh_completion.install "completions/blox.zsh" => "_blox"
        fish_completion.install "completions/blox.fish"
      end
    end
  end

  test do
    system "#{bin}/blox -v"
  end
end
