# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drb < Formula
  desc "DevRel Blox"
  homepage "https://github.com/devrel-blox/"
  version "0.1.15"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.15/drb_0.1.15_darwin_amd64.tar.gz"
    sha256 "056ffd2fb235e28583f83aaa6a6ec42bb22058d669481b13b8197b776fa7b89e"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.15/drb_0.1.15_darwin_arm64.tar.gz"
    sha256 "24ea687b5bfb0594100f0bde5fd2d82e7156d3c67c47d4adf6f1a37f0e742ebd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.15/drb_0.1.15_linux_amd64.tar.gz"
    sha256 "40da3e267e199767d0f73227e39f79aabeb1e2798ac288fa4e43e55961544a29"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.15/drb_0.1.15_linux_arm64.tar.gz"
    sha256 "2c97c37aa0fe35ca565ecb0492ec05336b28007cdd92e4eca524fb9853e01af6"
  end

  def install
    bin.install "drb"
  end
end
