# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drb < Formula
  desc "DevRel Blox"
  homepage "https://github.com/devrel-blox/"
  version "0.1.11"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.11/drb_0.1.11_darwin_amd64.tar.gz"
    sha256 "16a85b5a18ae6889d5419f6534864b8d6bc1301ffa0d6e9a025df1842ed2feae"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.11/drb_0.1.11_darwin_arm64.tar.gz"
    sha256 "778af4314f4d0454c25f1840509cc18954f158fccf85cb883459eaa6c8a5c5c2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.11/drb_0.1.11_linux_amd64.tar.gz"
    sha256 "56361024162ea993f52da936e42b6b2c8a0ed2e44b631191a272c0bc7fa6a690"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/devrel-blox/drb/releases/download/v0.1.11/drb_0.1.11_linux_arm64.tar.gz"
    sha256 "3465f5b364c27ce80d74ad4f0a1a05ea940fb8708a65e9739a247b4b591e18f6"
  end

  def install
    bin.install "drb"
  end
end
